//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnosis
    {
        public int ID { get; set; }
        public string Analysis { get; set; }
        public int AnalysisID { get; set; }
    
        public virtual DOCTORS_1 DOCTORS_1 { get; set; }
    }
}
