//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication6
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTORS_1
    {
        public DOCTORS_1()
        {
            this.Patient = new HashSet<Patient>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> HospitalID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Diagnosis Diagnosis { get; set; }
        public virtual Hospital Hospital { get; set; }
        public virtual ICollection<Patient> Patient { get; set; }
    }
}
