//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication6
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalEntities : DbContext
    {
        public HospitalEntities()
            : base("name=HospitalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admin { get; set; }
        public DbSet<Analysis> Analysis { get; set; }
        public DbSet<Diagnosis> Diagnosis { get; set; }
        public DbSet<DOCTORS_1> DOCTORS_1 { get; set; }
        public DbSet<Engineer_1> Engineer_1 { get; set; }
        public DbSet<Hospital> Hospital { get; set; }
        public DbSet<Laboratory> Laboratory { get; set; }
        public DbSet<Patient> Patient { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Type_of_analysis> Type_of_analysis { get; set; }
    }
}
